# Generated by Django 5.1.5 on 2025-02-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizb', '0002_alter_teammember_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Optional icon image if not using FontAwesome', upload_to='service/icons'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order on the website'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fa-code')", max_length=50),
        ),
    ]
